package com.mindrift.integrity.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.mindrift.integrity.entity.ViolationType;
import jakarta.validation.constraints.NotNull;
import lombok.Builder;
import lombok.Value;
import lombok.extern.jackson.Jacksonized;

import java.time.Instant;
import java.util.UUID;

/**
 * Payload received from the browser SDK on POST /api/integrity/violations.
 *
 * The client reports one event per call. Batching is handled client-side
 * and each violation is sent independently to maintain ordering guarantees.
 */
@Value
@Builder
@Jacksonized
@JsonInclude(JsonInclude.Include.NON_NULL)
public class ReportViolationRequest {

    @NotNull
    UUID attemptId;

    /** Optional: for competition-context attempts */
    UUID competitionId;

    @NotNull
    ViolationType violationType;

    /**
     * Seconds elapsed since the attempt started.
     * Used to correlate with time-on-task for scoring adjustments.
     */
    Long elapsedSeconds;

    /**
     * Arbitrary JSON from the client SDK (window dimensions, clipboard text length,
     * devtools width delta, etc.). Stored verbatim for audit purposes.
     *
     * Example: {"tabTitle":"Google","windowWidth":1280,"windowHeight":720}
     */
    String evidenceJson;

    /** Human-readable description generated by the client SDK */
    String description;

    /** ISO-8601 timestamp from the client at moment of detection */
    Instant occurredAt;
}
