package com.mindrift.ai.entity;

import com.mindrift.common.base.BaseEntity;
import com.mindrift.user.entity.User;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.util.UUID;

/**
 * Represents a complete quiz generated by AI and awaiting review/publication.
 *
 * AI-generated quizzes start in DRAFT status. A creator or admin reviews
 * and publishes them. The full quiz structure (title, questions, options)
 * is stored as JSON for easy editing before committing to the quizzes table.
 */
@Getter
@Setter
@Entity
@Table(
    name = "generated_quizzes",
    indexes = {
        @Index(name = "idx_gq_user",      columnList = "user_id"),
        @Index(name = "idx_gq_status",    columnList = "status"),
        @Index(name = "idx_gq_request",   columnList = "ai_request_id")
    }
)
public class GeneratedQuiz extends BaseEntity {

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ai_request_id")
    private AIRequest aiRequest;

    // ─── Generation parameters ────────────────────────────────────────────
    @Column(name = "topic", nullable = false, columnDefinition = "TEXT")
    private String topic;

    @Column(name = "category_id")
    private UUID categoryId;

    @Column(name = "category_name", length = 100)
    private String categoryName;

    @Column(name = "difficulty", length = 20)
    private String difficulty;

    @Column(name = "requested_question_count")
    private Integer requestedQuestionCount = 10;

    @Column(name = "generated_question_count")
    private Integer generatedQuestionCount = 0;

    // ─── Status ───────────────────────────────────────────────────────────
    /** GENERATING | DRAFT | REVIEWING | PUBLISHED | REJECTED | FAILED */
    @Column(name = "status", nullable = false, length = 20)
    private String status = "GENERATING";

    // ─── Generated content ────────────────────────────────────────────────
    @Column(name = "generated_title", length = 200)
    private String generatedTitle;

    @Column(name = "generated_description", columnDefinition = "TEXT")
    private String generatedDescription;

    /**
     * Full quiz structure as JSON:
     * { title, description, questions: [{ text, options, correctIndex, explanation }] }
     */
    @Column(name = "quiz_json", columnDefinition = "JSONB")
    private String quizJson;

    // ─── Published quiz reference ─────────────────────────────────────────
    /** Set after the generated quiz is committed to the quizzes table */
    @Column(name = "published_quiz_id")
    private UUID publishedQuizId;

    // ─── Review notes ─────────────────────────────────────────────────────
    @Column(name = "reviewer_notes", columnDefinition = "TEXT")
    private String reviewerNotes;
}
